openapi: 3.1.0
info:
  title: Sommelier API
  version: 1.0.0
servers:
  - url: https://sommelier2.onrender.com
paths:
  /add-wine:
    post:
      operationId: addWine
      summary: Voeg een wijn toe aan Airtable
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                domain:
                  type: string
                name:
                  type: string
                year:
                  type: integer
                type:
                  type: string
                average_rating:
                  type: number
                domain_price:
                  type: number
                retail_price:
                  type: number
                drink_period_start:
                  type: integer
                drink_period_end:
                  type: integer
                description:
                  type: string
                recommendations:
                  type: string
                status:
                  type: string
              required:
                - domain
                - name
                - year
                - status
      responses:
        "200":
          description: Wijn toegevoegd
