openapi: 3.1.0
info:
  title: Sommelier API
  version: 1.0.0
servers:
  - url: https://sommelier2.onrender.com
paths:
  /add-wine:
    post:
      operationId: addWine
      summary: Voeg een wijn toe aan Airtable
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                domain:
                  type: string
                name:
                  type: string
                year:
                  type: integer
                type:
                  type: string
                average_rating:
                  type: number
                domain_price:
                  type: number
                retail_price:
                  type: number
                drink_period_start:
                  type: integer
                drink_period_end:
                  type: integer
                description:
                  type: string
                recommendations:
                  type: string
                status:
                  type: string
              required:
                - domain
                - name
                - year
                - status
      responses:
        "200":
          description: Wijn toegevoegd
  /list-wines:
  get:
    operationId: listWines
    summary: Haal beschikbare wijnen op, optioneel gefilterd op type
    parameters:
        - in: query
          name: type
          schema:
            type: string
            enum: [Red, White, Rosé]
          description: Het soort wijn (Red, White, Rosé)
        - in: query
          name: is_prime
          schema:
            type: boolean
          description: Filter op wijnen die nu op dronk zijn (TRUE betekent filteren)
    responses:
      "200":
        description: Lijst van wijnen
        content:
          application/json:
            schema:
              type: object
              properties:
                success:
                  type: boolean
                records:
                  type: array
                  items:
                    type: object
                    properties:
                      domain:
                        type: string
                      name:
                        type: string
                      year:
                        type: integer
                      type:
                        type: string
                      average_rating:
                        type: number
                      domain_price:
                        type: number
                      retail_price:
                        type: number
                      drink_period_start:
                        type: integer
                      drink_period_end:
                        type: integer
                      description:
                        type: string
                      recommendations:
                        type: string
                      status:
                        type: string

